### ISSUE TITLE
最大化窗口以后URL列表框没有放大

### ISSUE THREAD

**Issue by zenglian** [xuncv/WechatVideoSniffer#13]
简单易用，谢谢！
1、最大化窗口以后URL列表框没有放大
2、凭URL无法判断视频内容以选择下载对象，最好每个url有一个preview小图。
3、chrome无法下载exe文件（https://support.google.com/chrome/answer/6261569?visit_id=638078805046949602-1127789513&p=ib_download_blocked&hl=zh-Hans&rd=1）

**Comment by FFFPrime** [comment]
> 简单易用，谢谢！ 1、最大化窗口以后URL列表框没有放大 2、凭URL无法判断视频内容以选择下载对象，最好每个url有一个preview小图。 3、chrome无法下载exe文件（[https://support.google.com/chrome/answer/6261569?visit_id=638078805046949602-1127789513&p=ib_download_blocked&hl=zh-Hans&rd=1）](https://support.google.com/chrome/answer/6261569?visit_id=638078805046949602-1127789513&p=ib_download_blocked&hl=zh-Hans&rd=1%EF%BC%89)

1. 你可以下载个aardio自己修改下窗口样式，小问题
2. 正常播放视频号会识别到很多链接吗？如果会的话同时预览多个视频可能会很卡，在视频里截图也很难认看出来是不是需要下载的视频，建议直接复制到浏览器预览
3. 改用其他浏览器谢谢
