### ISSUE TITLE
非程序本身相关 - 微信视频号文件格式问题

### ISSUE THREAD

**Issue by salicaceae** [xuncv/WechatVideoSniffer#15]
通过程序嗅探链接下载的文件是MP4格式，与其他途径获得的视频文件大小基本一致，但是嗅探链接下载到的文件通常的视频播放软件不能识别和播放。请教各位是否有方式转换或解析文件格式？

原来关闭的10号提问已经提过这个问题了，该提问就也关闭吧。
不过还是没找到解决的办法。

**Comment by xuncv** [comment]
试试readme的这个方案呢
目前初步分析微信视频对流媒体进行加密，尚无逆向方法，可采用如下方法绕过：

视频转发至文件传输助手，然后关闭微信视频窗口
从文件传输助手打开视频，即可抓到未加密的视频地址

**Comment by xuncv** [comment]
其他途径是如何获取的，有开源方案吗

**Comment by sipieng** [comment]
> 试试readme的这个方案呢 目前初步分析微信视频对流媒体进行加密，尚无逆向方法，可采用如下方法绕过：
> 
> 视频转发至文件传输助手，然后关闭微信视频窗口 从文件传输助手打开视频，即可抓到未加密的视频地址

这个方法这几天似乎已失效，至少在我的PC微信3.8.1.26上是如此。可能微信重新加密了。

**Comment by aweffr** [comment]
插眼

**Comment by geekswg** [comment]
用不了，应该失效了

**Comment by xuncv** [comment]
> 用不了，应该失效了

可以参考这个 issues https://github.com/xuncv/WechatVideoSniffer/issues/23

**Comment by geekswg** [comment]
应该是腾讯加密了视频流，现在那个方法已经绕不过加密了，建议开个置顶说明下。
