### ISSUE TITLE
现在取到的视频号链接，浏览器地址栏里打不开了

### ISSUE THREAD

**Issue by luochaolun** [xuncv/WechatVideoSniffer#16]
就最近几天的事儿，之前还可以，应该是微信又升级了。

**Comment by china5188** [comment]
1月视频号流媒体加密以后，下载正常下载，但不能观看了，那么那些付费的机器人小程序是怎么得到未加密的地址的？

**Comment by xuncv** [comment]
可以参考这个 issues https://github.com/xuncv/WechatVideoSniffer/issues/23
