### ISSUE TITLE
目前无法正常下载了。

### ISSUE THREAD

**Issue by lctzgsh** [xuncv/WechatVideoSniffer#17]
这软件目前无法正常下载了。求新方法

**Comment by luguoyixiazi** [comment]
真他妈崽种啊鹅，加密增强了，现在这种传统手段都不行了

**Comment by dawnyangcat** [comment]
没法用了吗  什么时候更新

**Comment by xuncv** [comment]
可以参考这个 issues https://github.com/xuncv/WechatVideoSniffer/issues/23
