### ISSUE TITLE
请问安装的根证书名是什么？

### ISSUE THREAD

**Issue by BeyondYu** [xuncv/WechatVideoSniffer#18]
想请问下作者最初安装时启用的根证书名称是什么？

近期因需下载了软件，但是微信视频数据加密了无法播放，也就用不上了，想清理得更干净些

**Comment by xuncv** [comment]
1. 微信视频加密有暂时解决方案。 可以参考这个 issues https://github.com/xuncv/WechatVideoSniffer/issues/23
2. 采用的是fiddler core库，证书搜索 fiddler即可
