### ISSUE TITLE
什么时候考虑下其他端的版本

### ISSUE THREAD

**Issue by f1024557668** [xuncv/WechatVideoSniffer#19]
是否会有发布其它端的打算啊

**Comment by china5188** [comment]
1月视频号流媒体加密以后，下载正常下载，但不能观看了，那么那些付费的机器人小程序是怎么得到未加密的地址的？

烦请UP主 更新下

**Comment by xuncv** [comment]
受fiddler core限制 只支持windows

**Comment by xuncv** [comment]
> 

可以参考这个 issues https://github.com/xuncv/WechatVideoSniffer/issues/23
