### ISSUE TITLE
提示下载完成后无法找到下载目录与文件

### ISSUE THREAD

**Issue by lovelystrange** [xuncv/WechatVideoSniffer#2]
在本机默认的下载文件夹内没有发现下载的视频。

**Comment by xuncv** [comment]
我还没遇到过这种情况，排查下是不是网络问题造成的下载超时

**Comment by lweo** [comment]
是在子目录下。你去./Downloads/download里找找

**Comment by CHEN-MAX-PRO** [comment]
> 是在子目录下。你去./Downloads/download里找找

可是在DOWNLOADS下面也没找到download这个文件夹
