### ISSUE TITLE
转发文件助手里的视频点击也是视频号窗口了嗅探下载的地址下载后还是无法播放

### ISSUE THREAD

**Issue by dcdlove** [xuncv/WechatVideoSniffer#21]

**Comment by china5188** [comment]
1月视频号流媒体加密以后，下载正常下载，但不能观看了，那么那些付费的机器人小程序是怎么得到未加密的地址的？****

**Comment by dcdlove** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xuncv** [comment]
可以参考这个 issues https://github.com/xuncv/WechatVideoSniffer/issues/23

**Comment by dcdlove** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
