### ISSUE TITLE
[Issue] WTF is this shit? The binary triggers a shit tons of warning flags

### ISSUE THREAD

**Issue by Xyde** [xuncv/WechatVideoSniffer#26]
Please tell me that how it's not a false positive when there's so many anti-virus engines flagging it /facepalm. 
https://www.virustotal.com/gui/file/7d49ce45c8a1679f0da52b92140d5b125f2b4eed97d5de0d16028241b3ecc706

Bruh, I'd feel safer if you just tell us how to compile/build this. But giving a binary outright that is not part of the **Releases** tab but as the source code. Nah man I'm not risking it... (Yeah WeChat videos are cool but not to the point of risking these flags...)

**Comment by xuncv** [comment]
right,right,right ^_^
