### ISSUE TITLE
PC微信显示“不支持的消息，可在手机上查看”

### ISSUE THREAD

**Issue by 1234zou** [xuncv/WechatVideoSniffer#6]
如题，现在PC微信没法看视频号了，转发给“文件传输助手”也不行，那如何实现在PC微信上打开视频呢？这一步做不到的话，后面也就不行了。

我试了PC微信3.5.0，也不行。请问有什么办法么？

**Comment by xuncv** [comment]
我用最新版的3.7.6  是可以用“文件传输助手“转发，pc打开的。可能你的视频有点特殊，或者微信本身遭到破坏

**Comment by 1234zou** [comment]
3.7.6我也用过，也不行，大概率是视频比较特殊，是视频号的直播回放。

**Comment by xuncv** [comment]
请提供一个有直播回放的视频号 ，我测试一下

**Comment by 1234zou** [comment]
十分感谢！微信搜索“南开化学”，点击搜索结果中的视频号（不要点公众号那个），然后点击直播回放，任选一个视频
![南开化学视频号_直播回放](https://user-images.githubusercontent.com/12122692/187022964-ea24c602-22e8-4390-9049-f1e3f9371be4.jpg)

**Comment by xuncv** [comment]
测试了下，pc微信不支持直播回放的视频消息。我尝试抓手机微信的数据，现在微信用的mmtls协议，用目前的组件是无法抓这个协议的包的。搜索了下，网络上也没有抓这个协议的方法的。
综合下来，目前的技术，直播的回放是无法提取的

**Comment by 1234zou** [comment]
十分感谢，麻烦了！

**Comment by lweo** [comment]
> 测试了下，pc微信不支持直播回放的视频消息。我尝试抓手机微信的数据，现在微信用的mmtls协议，用目前的组件是无法抓这个协议的包的。搜索了下，网络上也没有抓这个协议的方法的。 综合下来，目前的技术，直播的回放是无法提取的

直播回放的缓存能提取吗？从闪存或从内存中提取可行吗

**Comment by lweo** [comment]
> 测试了下，pc微信不支持直播回放的视频消息。我尝试抓手机微信的数据，现在微信用的mmtls协议，用目前的组件是无法抓这个协议的包的。搜索了下，网络上也没有抓这个协议的方法的。 综合下来，目前的技术，直播的回放是无法提取的

https://youtu.be/amQr5fs00N0  这个是怎么实现的？
