### ISSUE TITLE
点击监听没反应，装不了证书 win7 64位 IE11

### ISSUE THREAD

**Issue by ahotcake** [xuncv/WechatVideoSniffer#7]
点击监听没反应，装不了证书
win7 64位 IE11

**Comment by kkxg** [comment]
同样的问题

**Comment by FFFPrime** [comment]
> 点击监听没反应，装不了证书 win7 64位 IE11

你认真的吗用IE，软件需要注入证书，可能权限不足/杀毒软件禁止，aardio写的东西基本连XP都能用
